[package]
name = "tracing-elastic-apm"
version = "3.0.0"
authors = ["Kamil Rojewski <kamil.rojewski@gmail.com>"]
edition = "2018"
description = "Elasting APM intake API tracing layer."
documentation = "https://docs.rs/tracing-elastic-apm"
homepage = "https://github.com/krojew/tracing-elastic-apm"
repository = "https://github.com/krojew/tracing-elastic-apm"
readme = "./README.md"
keywords = ["tracing", "elastic", "apm", "telemetry"]
license = "MIT"

[dependencies]
base64 = "0.13"
fxhash = "0.2"
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2", default-features = false }
version = "3.0"
anyhow = "1.0.42"

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]
